###########

#   BetterKMR for Chrome
#   Copyright (C) 2025 InterLabs

#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.

#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.

#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

###########
# themes.yml - src/config/themes.yml #

#  List of themes, in order, that get asynchronously loaded as CSS themes on school.kiwi pages.
#  Note that if an error occurs in a theme, it doesn't halt the execution of the next themes.
#  Don't forget to append your theme(s) in "web_accessible_resources" in manifest.json.

0:
    name: "Space Theme"
    css: "space.css"
    thumbnail: "images/backgrounds/space.jpg"
    author: "Convy32"
    highlight: "The default Space theme, bundled with BetterKMR by default."
    description: "The default Space theme, bundled with BetterKMR by default. Extra content here."
1:
    name: "School Colours"
    css: "blank.css"
    highlight: "Use your school's default colours"
2:
    name: "Vivid Winter"
    css: "vivid.css"
    thumbnail: "images/backgrounds/vivid.jpeg"
    author: "Solar"
    highlight: "A chill winter theme with a background so great it can't be artificial intelligence."
    description: "It actually can't be artificial intelligence! Wait, I'm second guessing... maybe it might."
3:
    name: "Star Destroyers"
    css: "starwarsempire.css"
    thumbnail: "images/backgrounds/starwarsempire_downscaled.jpg"
    author: "Samuel H"
    highlight: "Rule through the fear of force rather than force itself. -Wilhuff Tarkin"
    description: "Rule through the fear of force rather than force itself. -Wilhuff Tarkin **Thank you for using this theme!**"
4:
    name: "Pure Dark Theme"
    css: "puredark.css"
    thumbnail: "images/thumbnails/pure-dark.png"
    author: "Solar"
    highlight: "When you just need that peace and quiet. It's silence for your screen."
    description: "When you just need that peace and quiet. It's silence for your screen. This theme is Vivid base but reskinned."