###########

#   BetterKMR for Chrome
#   Copyright (C) 2025 InterLabs

#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.

#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.

#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

###########
# themes.yml - src/config/themes.yml #

#  List of themes, in order, that get asynchronously loaded as CSS themes on school.kiwi pages.
#  Note that if an error occurs in a theme, it doesn't halt the execution of the next themes.

0:
  name: "Space Theme"
  css: "space.css"
  thumbnail: "images/backgrounds/space.jpg"
  author: "Convy32"
  highlight: "The default Space theme, the BetterKMR default. (📸 Wallpapers.com)"
  tags:
    "Default": "rgba(153,153,153,0.5)"
    "Recommended": "rgba(119,52,235,0.5)"
    "Space": "rgba(52,101,235,0.5)"
1:
  name: "School Colours"
  css: "blank.css"
  highlight: "Use your school's default colours"
  tags:
    "School": "rgba(76, 175, 80, 0.5)"
    "Default": "rgba(153,153,153,0.5)"
2:
  name: "Vivid Winter"
  css: "vivid.css"
  js: "vivid.js"
  thumbnail: "images/backgrounds/vivid-rain-thumbnail.png"
  author: "Solar"
  highlight: "A chill winter theme with a cozy background. (📸 Attribution to @LofiPlace on Pixabay)"
  description: "vivid.md"
  tags:
    "Winter": "rgba(168,254,255,0.5)"
    "Christmas": "rgba(255,38,71,0.5)"
    "Cozy": "rgba(255,165,48,0.5)"
    "Animated": "rgba(156,102,0,0.5)"
3:
  name: "Star Destroyers"
  css: "starwarsempire.css"
  thumbnail: "images/backgrounds/star_destroyers_updated.png"
  author: "Samuel H"
  highlight: "Rule through the fear of force rather than force itself. -Wilhuff Tarkin (📸 Star Wars | EAW)"
  tags:
    "Star Wars": "rgba(255, 191, 0, 0.5)"
    "Dark Side": "rgba(213, 0, 0, 0.5)"
    "Sci-Fi": "rgba(89, 111, 128, 0.5)"
4:
  name: "Pure Dark Theme"
  css: "puredark.css"
  thumbnail: "images/thumbnails/pure-dark.png"
  author: "Solar"
  highlight: "When you just need that peace and quiet. It's silence for your screen."
  tags:
    "Dark": "rgba(0, 0, 0, 0.5)"
    "Minimal": "rgba(128, 128, 128, 0.5)"
    "Simple": "rgba(64, 64, 64, 0.5)"
5:
  name: "Mountain Slideshow"
  css: "slideshow.css"
  js: "slideshow.js"
  thumbnail: "images/thumbnails/mountain-slideshow.jpg"
  author: "Solar"
  highlight: "External JavaScript theme example, with six mountain images. (📸 Various @ Unsplash)"
  tags:
    "Mountain": "rgba(79, 132, 102, 0.5)"
    "Slideshow": "rgba(156, 163, 175, 0.5)"
    "JavaScript": "rgba(247, 223, 30, 0.5)"
6:
  name: "Pure Light Theme"
  css: "purelight.css"
  thumbnail: "images/thumbnails/pure-light.png"
  author: "Solar"
  highlight: "Not the best theme if you want to keep your eyes safe."
  tags:
    "Light": "rgba(255, 255, 255, 0.5)"
    "Minimal": "rgba(220, 220, 220, 0.5)"
    "Simple": "rgba(240, 240, 240, 0.5)"