name: Build Extensions

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare manifest for Firefox
        if: matrix.browser == 'firefox'
        run: |
          # Update the manifest for Firefox by replacing the service_worker key
          sed -i 's/"service_worker": "service.js"/"scripts": ["service.js"]/' manifest.json
          echo "Modified manifest for Firefox:"
          cat manifest.json

      - name: Build extension
        run: |
          echo "Building extension for ${{ matrix.browser }}"
          # Create a zip file containing the extension files.
          # Adjust the zip command if you need to exclude/include specific files.
          zip -r extension-${{ matrix.browser }}.zip .

      - name: Upload extension artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: extension-${{ matrix.browser }}
          path: extension-${{ matrix.browser }}.zip
