name: Build Extensions

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build extensions
        run: npm run build:all
        
      - name: Upload Chrome extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-chrome
          path: dist/chrome/
          compression-level: 9

      - name: Upload Firefox extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-firefox
          path: dist/firefox/
          compression-level: 9